<a href="https://colab.research.google.com/github/anshupandey/ms-generativeai-apr2025/blob/main/code14_Embeddings_and_vectorDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploring Embeddeings from OpenAI

In [ ]:
import os

In [1]:
from langchain_openai import OpenAIEmbeddings
embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

In [2]:
v1,v2,v3 = embeddings.embed_documents(["I like python programming, its a good programming language.",
                                    "Python is an amazing programming language, i like it a lot.",
                                    "Hello World, how are you?"])

In [3]:
print(v1)

[0.013009362854063511, -0.05697955563664436, 0.014649808406829834, -0.0010447462555021048, 0.026371732354164124, -0.018460212275385857, 0.04771830141544342, 0.045351073145866394, -0.011877662502229214, -0.005985552445054054, -0.004820108879357576, -0.06648998707532883, -0.044105164706707, 0.015355823561549187, 0.014473305083811283, 0.028884314000606537, -0.030296344310045242, 0.013985324651002884, 0.010605797171592712, -0.001959710381925106, -0.009183384478092194, 0.007563703693449497, -0.003322422970086336, 0.03525921329855919, 0.0447281189262867, -0.05714567378163338, -0.00048538524424657226, 0.038041744381189346, -0.01446292269974947, 0.02537500485777855, 0.01624872535467148, -0.008710977621376514, -0.040948864072561264, 0.029548799619078636, -0.02145039290189743, -0.061547886580228806, 0.04692922532558441, -0.028365185484290123, 0.05349101126194, -0.017951466143131256, 0.013123570941388607, -0.018366768956184387, 0.03523844853043556, -0.013943794183433056, -0.03330729156732559, 0.0

In [4]:
len(v1), len(v2), len(v3)

(1536, 1536, 1536)

In [5]:
from numpy.linalg import norm
import numpy as np
# cosine similarity
np.dot(v1,v2)/(norm(v1),norm(v2))

array([0.72315984, 0.72315985])

In [6]:
from numpy.linalg import norm
import numpy as np

np.dot(v1,v3)/(norm(v1),norm(v3))

array([0.22775642, 0.22775644])

In [7]:
from numpy.linalg import norm
import numpy as np

np.dot(v2,v3)/(norm(v2),norm(v3))

array([0.23818116, 0.23818118])

## Vector Database: **ChromaDB**

In [8]:
import chromadb
chroma_client = chromadb.Client()

In [9]:
collection = chroma_client.create_collection(name="my_collection")

In [10]:
collection.add(
    embeddings=[[1.2, 2.3, 4.5], [6.7, 8.2, 9.2]],
    documents=["Python is a programming language", "langchain is an framework"],
    metadatas=[{"source": "my_source"}, {"source": "my_source"}],
    ids=["id1", "id2"]
)

In [12]:
results = collection.query(
    query_embeddings=[[0.1, 2.1, 3.1]],
    n_results=1
)
results

{'ids': [['id1']],
 'embeddings': None,
 'documents': [['Python is a programming language']],
 'uris': None,
 'data': None,
 'metadatas': [[{'source': 'my_source'}]],
 'distances': [[3.2100002765655518]],
 'included': [<IncludeEnum.distances: 'distances'>,
  <IncludeEnum.documents: 'documents'>,
  <IncludeEnum.metadatas: 'metadatas'>]}