<a href="https://colab.research.google.com/github/anshupandey/ms-generativeai-apr2025/blob/main/code14_Embeddings_and_vectorDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploring Embeddeings from OpenAI

In [ ]:
import os

In [ ]:
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

In [ ]:
v1,v2,v3 = embeddings.embed_documents(["I like python programming, its a good programming language.",
                                    "Python is an amazing programming language, i like it a lot.",
                                    "Hello World, how are you?"])

In [ ]:
print(v1)

[0.012993532232940197, -0.05691416189074516, 0.014654046855866909, -0.0010118765057995915, 0.026319166645407677, -0.018442098051309586, 0.04769830033183098, 0.0453735813498497, -0.011851928196847439, -0.005988233257085085, -0.004825872369110584, -0.06650363653898239, -0.04416970536112785, 0.015339009463787079, 0.014487995766103268, 0.028892965987324715, -0.030325159430503845, 0.013958706520497799, 0.01060654129832983, -0.001987429102882743, -0.009210670366883278, 0.007555344607681036, -0.0032873013988137245, 0.03524443507194519, 0.0447508879005909, -0.057163238525390625, -0.0004919925122521818, 0.03802580013871193, -0.014498374424874783, 0.02538512647151947, 0.016231536865234375, -0.008665814064443111, -0.04093170166015625, 0.02955717220902443, -0.021441403776407242, -0.061605118215084076, 0.04699258133769035, -0.02835329808294773, 0.05355161800980568, -0.017933564260601997, 0.013149205595254898, -0.01841096393764019, 0.03524443507194519, -0.013875680975615978, -0.033272575587034225, 0

In [ ]:
len(v1), len(v2), len(v3)

(1536, 1536, 1536)

In [ ]:
from numpy.linalg import norm
import numpy as np
# cosine similarity
np.dot(v1,v2)/(norm(v1),norm(v2))

array([0.72327076, 0.72327076])

In [ ]:
from numpy.linalg import norm
import numpy as np

np.dot(v1,v3)/(norm(v1),norm(v3))

array([0.22764423, 0.22764423])

In [ ]:
from numpy.linalg import norm
import numpy as np

np.dot(v2,v3)/(norm(v2),norm(v3))

array([0.23810356, 0.23810356])

## Vector Database: **ChromaDB**

In [ ]:
import chromadb
chroma_client = chromadb.Client()

In [ ]:
collection = chroma_client.create_collection(name="my_collection")

In [ ]:
collection.add(
    embeddings=[[1.2, 2.3, 4.5], [6.7, 8.2, 9.2]],
    documents=["Python is a programming language", "langchain is an framework"],
    metadatas=[{"source": "my_source"}, {"source": "my_source"}],
    ids=["id1", "id2"]
)

In [ ]:
results = collection.query(
    query_embeddings=[[7.1, 9.1, 6.1]],
    n_results=1
)
results

{'ids': [['id2']],
 'distances': [[10.580000877380371]],
 'metadatas': [[{'source': 'my_source'}]],
 'embeddings': None,
 'documents': [['langchain is an framework']],
 'uris': None,
 'data': None}